---
title: "Scrape journal from fulltext"
subtitle: "Analyses of Psychology/APA dataset"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

# TODO

- NA

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

# Dependencies

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)
library(janitor)

```

# Data

```{r}

data_fulltexts <- read_rds("../../data/raw/psychology/data_fulltexts.rds")

```

# Scrape journal journals from text

```{r}

data_journals <- data_fulltexts |>
  # for testing
  #sample_n(3000)
  # near the top of each file the article info is listed. journal is listed between "by:" and "database" but doesn't have its own field (e.g., "journal:"). Pull out this substring for additional processing.
  mutate(text = str_extract(text, "by:\\s*(.*?)\\s*database:")) |>
  # match to known list of journals. this list was iteratively expanded by inspecting the text variable until all cases were covered. 
  mutate(journal = case_when(
    str_detect(text, "american journal of orthopsychiatry,") ~ "american journal of orthopsychiatry",
    str_detect(text, "asian american journal of psychology,") ~ "asian american journal of psychology",
    str_detect(text, "behavior analysis: research and practice,") ~ "behavior analysis: research and practice",
    str_detect(text, "behavioral development,") ~ "behavioral development",
    str_detect(text, "canadian journal of experimental psychology") ~ "canadian journal of experimental psychology",
    str_detect(text, "canadian psychology") ~ "canadian psychology",
    str_detect(text, "clinical practice in pediatric psychology,") ~ "clinical practice in pediatric psychology",
    str_detect(text, "clinical psychology: science and practice,") ~ "clinical psychology: science and practice",
    str_detect(text, "clinician's research digest: adult populations,") ~ "clinician's research digest: adult populations",
    str_detect(text, "clinician's research digest: child and adolescent populations,") ~ "clinician's research digest: child and adolescent populations",
    str_detect(text, "couple and family psychology: research and practice,") ~ "couple and family psychology: research and practice",
    str_detect(text, "cultural diversity & ethnic minority psychology,") ~ "cultural diversity & ethnic minority psychology",
    str_detect(text, "evolutionary behavioral sciences,") ~ "evolutionary behavioral sciences",
    str_detect(text, "experimental and clinical psychopharmacology,") ~ "experimental and clinical psychopharmacology",
    str_detect(text, "health psychology journal,") ~ "health psychology journal",
    str_detect(text, "the humanistic psychologist,") ~ "the humanistic psychologist",
    str_detect(text, "international journal of play therapy,") ~ "international journal of play therapy",
    str_detect(text, "international journal of stress management,") ~ "international journal of stress management",
    str_detect(text, "journal of applied psychology,") ~ "journal of applied psychology",
    str_detect(text, "journal of applied research in memory and cognition,") ~ "journal of applied research in memory and cognition",
    str_detect(text, "journal of comparative psychology,") ~ "journal of comparative psychology",
    str_detect(text, "journal of consulting and clinical psychology,") ~ "journal of consulting and clinical psychology",
    str_detect(text, "journal of counseling psychology,") ~ "journal of counseling psychology",
    str_detect(text, "journal of diversity in higher education,") ~ "journal of diversity in higher education",
    str_detect(text, "journal of educational psychology,") ~ "journal of educational psychology",
    str_detect(text, "journal of experimental psychology: animal learning and cognition,") ~ "journal of experimental psychology: animal learning and cognition",
    str_detect(text, "journal of experimental psychology: applied,") ~ "journal of experimental psychology: applied",
    str_detect(text, "journal of experimental psychology: general,") ~ "journal of experimental psychology: general",
    str_detect(text, "journal of experimental psychology: human perception and performance,") ~ "journal of experimental psychology: human perception and performance",
    str_detect(text, "journal of family psychology,") ~ "journal of family psychology",
    str_detect(text, "journal of latinx psychology,") ~ "journal of latinx psychology",
    str_detect(text, "journal of occupational health psychology,") ~ "journal of occupational health psychology",
    str_detect(text, "journal of personality and social psychology,") ~ "journal of personality and social psychology",
    str_detect(text, "journal of psychopathology and clinical science,") ~ "journal of psychopathology and clinical science",
    str_detect(text, "journal of psychotherapy integration,") ~ "journal of psychotherapy integration",
    str_detect(text, "journal of rural mental health,") ~ "journal of rural mental health",
    str_detect(text, "journal of theoretical and philosophical psychology,") ~ "journal of theoretical and philosophical psychology",
    str_detect(text, "journal of threat assessment and management,") ~ "journal of threat assessment and management",
    str_detect(text, "law and human behavior,") ~ "law and human behavior",
    str_detect(text, "motivation science,") ~ "motivation science",
    str_detect(text, "peace and conflict: journal of peace psychology,") ~ "peace and conflict: journal of peace psychology",
    str_detect(text, "practice innovations,") ~ "practice innovations",
    str_detect(text, "professional psychology: research and practice,") ~ "professional psychology: research and practice",
    str_detect(text, "psychiatric rehabilitation journal,") ~ "psychiatric rehabilitation journal",
    str_detect(text, "psychoanalytic psychology,") ~ "psychoanalytic psychology",
    str_detect(text, "psychological bulletin journal,") ~ "psychological bulletin",
    str_detect(text, "psychological methods,") ~ "psychological methods",
    str_detect(text, "psychological review,") ~ "psychological review",
    str_detect(text, "psychological services,") ~ "psychological services",
    str_detect(text, "psychology & neuroscience,") ~ "psychology & neuroscience",
    str_detect(text, "psychology and aging,") ~ "psychology and aging",
    str_detect(text, "psychology of addictive behaviors,") ~ "psychology of addictive behaviors",
    str_detect(text, "psychology of leaders and leadership,") ~ "psychology of leaders and leadership",
    str_detect(text, "psychology of men & masculinities,") ~ "psychology of men & masculinities",
    str_detect(text, "psychology of popular media,") ~ "psychology of popular media",
    str_detect(text, "psychology of religion and spirituality,") ~ "psychology of religion and spirituality",
    str_detect(text, "psychology of sexual orientation and gender diversity,") ~ "psychology of sexual orientation and gender diversity",
    str_detect(text, "psychology of violence,") ~ "psychology of violence",
    str_detect(text, "qualitative psychology,") ~ "qualitative psychology",
    str_detect(text, "rehabilitation psychology,") ~ "rehabilitation psychology",
    str_detect(text, "scholarship of teaching and learning in psychology,") ~ "scholarship of teaching and learning in psychology",
    str_detect(text, "spirituality in clinical practice,") ~ "spirituality in clinical practice",
    str_detect(text, "translational issues in psychological science,") ~ "translational issues in psychological science",
    str_detect(text, "training and education in professional psychology,") ~ "training and education in professional psychology",
    str_detect(text, "families, systems, & health,") ~ "families, systems, & health",
    str_detect(text, "group dynamics: theory, research, and practice,") ~ "group dynamics: theory, research, and practice",
    str_detect(text, "journal of experimental psychology: learning, memory, and cognition,") ~ "journal of experimental psychology: learning, memory, and cognition",
    str_detect(text, "journal of neuroscience, psychology, and economics,") ~ "journal of neuroscience, psychology, and economics",
    str_detect(text, "personality disorders: theory, research, and treatment,") ~ "personality disorders: theory, research, and treatment",
    str_detect(text, "psychological trauma: theory, research, practice, and policy,") ~ "psychological trauma: theory, research, practice, and policy",
    str_detect(text, "psychology of aesthetics, creativity, and the arts,") ~ "psychology of aesthetics, creativity, and the arts",
    str_detect(text, "psychology of consciousness: theory, research, and practice,") ~ "psychology of consciousness: theory, research, and practice",
    str_detect(text, "psychology, public policy, and law,") ~ "psychology, public policy, and law",
    str_detect(text, "psychomusicology: music, mind, and brain,") ~ "psychomusicology: music, mind, and brain",
    str_detect(text, "sport, exercise, and performance psychology,") ~ "sport, exercise, and performance psychology",
    str_detect(text, "technology, mind, and behavior,") ~ "technology, mind, and behavior",
    str_detect(text, "psychological assessment,") ~ "psychological assessment",
    str_detect(text, "behavioral neuroscience,") ~ "behavioral neuroscience",
    str_detect(text, "history of psychology,") ~ "history of psychology",
    str_detect(text, "american psychologist,") ~ "american psychologist",
    str_detect(text, "neuropsychology,") ~ "neuropsychology",
    str_detect(text, "decision,") ~ "decision",
    str_detect(text, "dreaming,") ~ "dreaming",
    str_detect(text, "traumatology,") ~ "traumatology",
    str_detect(text, "stigma and health,") ~ "stigma and health",
    str_detect(text, "school psychology,") ~ "school psychology",
    str_detect(text, "psychotherapy: theory, research, practice, training,") ~ "psychotherapy: theory, research, practice, training",
    str_detect(text, "consulting psychology,") ~ "consulting psychology",
    str_detect(text, "developmental psychology,") ~ "developmental psychology",
    str_detect(text, "health psychology,") ~ "health psychology",
    str_detect(text, "journal of abnormal psychology,") ~ "journal of abnormal psychology",
    str_detect(text, "psychology of men &amp; masculinity, ") ~ "psychology of men & masculinities",
    str_detect(text, "psychological bulletin,") ~ "psychological bulletin",
    str_detect(text, "sport, exercise, and performance psychology,") ~ "sport, exercise, and performance psychology",
    str_detect(text, "canadian journal of psychology") ~ "canadian journal of psychology",
    str_detect(text, "consulting psychology journal: practice and research,") ~ "consulting psychology journal: practice and research",
    str_detect(text, "canadian journal of behavioural science") ~ "canadian journal of behavioural science",
    str_detect(text, "military psychology,") ~ "military psychology",
    str_detect(text, "cultural diversity and ethnic minority psychology,") ~ "cultural diversity and ethnic minority psychology",
    str_detect(text, "cultural diversity and mental health,") ~ "cultural diversity and mental health",
    str_detect(text, "psychomusicology: music, mind and brain,") ~ "psychomusicology: music, mind and brain",
    str_detect(text, "psychosocial rehabilitation journal,") ~ "psychosocial rehabilitation journal",
    str_detect(text, "psychomusicology: a journal of research in music cognition,") ~ "psychomusicology: a journal of research in music cognition",
    str_detect(text, "school psychology quarterly,") ~ "school psychology quarterly",
    str_detect(text, "health: the journal of collaborative family healthcare,") ~ "health: the journal of collaborative family healthcare",
    str_detect(text, "review of general psychology,") ~ "review of general psychology",
    str_detect(text, "international perspectives in psychology: research, practice, consultation") ~ "international perspectives in psychology: research, practice, consultation",
    str_detect(text, "psychology of popular media culture, ") ~ "psychology of popular media culture",
    str_detect(text, "journal of social, evolutionary, and cultural psychology, ") ~ "journal of social, evolutionary, and cultural psychology",
    str_detect(text, "psychotherapy,") ~ "psychotherapy",
    str_detect(text, "emotion,") ~ "emotion",
  )) |>
  select(-text) |>
  drop_na()

```

# Categorize journals into fields

```{r}

# behaviorism
j_behaviorism <- c(
  "behavior analysis: research and practice"
)

# clinical
j_clincial <- c(
  "clinical psychology: science and practice",
  "clinician's research digest: adult populations",
  "clinician's research digest: child and adolescent populations",
  "couple and family psychology: research and practice",
  "journal of consulting and clinical psychology",
  "journal of counseling psychology",
  "journal of psychopathology and clinical science",
  "journal of psychotherapy integration",
  "journal of rural mental health",
  "professional psychology: research and practice",
  "psychiatric rehabilitation journal",
  "psychoanalytic psychology",
  "psychology of addictive behaviors",
  "traumatology",
  "psychotherapy: theory, research, practice, training",
  "consulting psychology",
  "spirituality in clinical practice",
  "personality disorders: theory, research, and treatment",
  "psychological trauma: theory, research, practice, and policy",
  "psychological assessment",
  "journal of abnormal psychology",
  "psychotherapy",
  "consulting psychology journal: practice and research",
  "international journal of play therapy",
  "experimental and clinical psychopharmacology"
)

# personality and social
j_personality_and_social <- c(
  "journal of personality and social psychology"
)

# developmental
j_developmental <- c(
  "behavioral development",
  "clinical practice in pediatric psychology",
  "developmental psychology"
)

# educational
j_educational <- c(
  "journal of diversity in higher education",
  "journal of educational psychology",
  "school psychology"
)

# applied
j_applied <- c(
  "journal of applied psychology",
  "journal of applied research in memory and cognition",
  "psychology of leaders and leadership",
  "translational issues in psychological science",
  "training and education in professional psychology"
)

# general
j_general <- c(
  "canadian psychology",
  "canadian journal of psychology",
  "asian american journal of psychology",
  "american psychologist",
  "school psychology quarterly",
  "health: the journal of collaborative family healthcare",
  "review of general psychology"
)

# cognitive and experimental 
j_cognitive_and_experimental <- c(
  "canadian journal of experimental psychology",
  "journal of experimental psychology: animal learning and cognition",
  "journal of experimental psychology: applied",
  "journal of experimental psychology: general",
  "journal of experimental psychology: human perception and performance",
  "journal of experimental psychology: learning, memory, and cognition",
  "emotion"
)

# health 
j_health <- c(
  "health psychology journal",
  "journal of occupational health psychology",
  "stigma and health",
  "health psychology"
)

# review
j_review <- c(
  "psychological bulletin",
  "psychological review"
)

# methods
j_methods <- c(
  "psychological methods"
)

# history and phil
j_history_and_philosophy <- c(
  "journal of theoretical and philosophical psychology",
  "history of psychology"
)

# neuro
j_neuro <- c(
  "psychology & neuroscience",
  "journal of neuroscience, psychology, and economics",
  "neuropsychology",
  "behavioral neuroscience"
)

# regional and diversity 
j_regional_and_diversity <- c(
  "cultural diversity & ethnic minority psychology",
  "journal of latinx psychology",
  "psychology of men & masculinity",
  "psychology of sexual orientation and gender diversity",
  "cultural diversity and ethnic minority psychology",
  "cultural diversity and mental health"
)

# other
j_other <- c(
  "families, systems, & health",
  "the humanistic psychologist",
  "american journal of orthopsychiatry",
  "international journal of stress management",
  "law and human behavior",
  "motivation science",
  "peace and conflict: journal of peace psychology",
  "practice innovations",
  "canadian journal of behavioural science",
  "evolutionary behavioral sciences",
  "journal of comparative psychology",
  "journal of family psychology",
  "journal of threat assessment and management",
  "psychological services",
  "psychology and aging",
  "psychology of popular media",
  "psychology of religion and spirituality",
  "psychology of violence",
  "qualitative psychology",
  "rehabilitation psychology",
  "scholarship of teaching and learning in psychology",
  "group dynamics: theory, research, and practice",
  "psychology of aesthetics, creativity, and the arts",
  "psychology of consciousness: theory, research, and practice",
  "psychology, public policy, and law",
  "psychomusicology: music, mind, and brain",
  "sport, exercise, and performance psychology",
  "technology, mind, and behavior",
  "decision",
  "dreaming",
  "sport, exercise, and performance psychology",
  "military psychology",
  "psychomusicology: music, mind and brain",
  "international perspectives in psychology: research, practice, consultation",
  "psychosocial rehabilitation journal",
  "psychomusicology: a journal of research in music cognition",
  "psychology of popular media culture",
  "journal of social, evolutionary, and cultural psychology"
)

data_journals_and_fields <- data_journals |>
  mutate(field = case_when(
    journal %in% j_behaviorism ~ "behaviorism",
    journal %in% j_clincial ~ "clinical",
    journal %in% j_personality_and_social ~ "personality/social",
    journal %in% j_developmental ~ "developmental",
    journal %in% j_educational ~ "educational",
    journal %in% j_applied ~ "applied",
    journal %in% j_general ~ "general",
    journal %in% j_cognitive_and_experimental ~ "cognitive/experimental",
    journal %in% j_health ~ "health",
    journal %in% j_review ~ "review",
    journal %in% j_methods ~ "methods",
    journal %in% j_history_and_philosophy ~ "history/philosophy",
    journal %in% j_neuro ~ "neuro",
    journal %in% j_regional_and_diversity ~ "regional/diversity",
    journal %in% j_other ~ "other"
  ))

```

# Write to disk

```{r}

write_rds(data_journals_and_fields, "../../data/processed/psychology/data_journals_and_fields.rds")

```

# Session info

```{r}

sessionInfo()

```


