# dev

## Check for false negatives

Copy a subset of html files whose dois returned no estimates to be hand checked.

```{r}

files <- data_fulltexts |>
  select(doi) |>
  anti_join(data_processed, by = "doi") |>
  sample_n(50) |>
  mutate(current = paste("../../data/apa_articles/", doi, "/fulltext.html", sep = ""),
         new = paste("../../data/for hand checking/", doi, ".html", sep = ""))

file.copy(from = files$current,
          to = files$new, 
          overwrite = TRUE, 
          recursive = FALSE, 
          copy.mode = TRUE)

```

## Check for false positives

```{r}

data_temp <- read_csv("../../data/processed/data_processed.csv") |>
  filter(!is.na(alpha) & 
           exclude_master == FALSE &
           regex_label != "α") |>
  select(doi, exemplar, alpha, all) |>
  # round alpha as in analysis
  mutate(alpha = janitor::round_half_up(alpha, 2),
         alpha = case_when(alpha == 0 ~ 0.01,
                           alpha == 1 ~ 0.99,
                           TRUE ~ alpha)) 

data_for_hand_checking_thresholds <- data_temp |>
  filter(alpha %in% c(.70, .80, .90)) |>
  sample_n(200)

data_for_hand_checking_non_thresholds <- data_temp |>
  filter(!alpha %in% c(.70, .80, .90)) |>
  sample_n(200)

data_for_hand_checking_thresholds |>
  slice(1:100) |>
  write_csv("../../data/for hand checking/checked for false positives/thresholds annika.csv")

data_for_hand_checking_thresholds |>
  slice(101:200) |>
  write_csv("../../data/for hand checking/checked for false positives/thresholds ian.csv")

data_for_hand_checking_non_thresholds |>
  slice(1:100) |>
  write_csv("../../data/for hand checking/checked for false positives/non thresholds annika.csv")

data_for_hand_checking_non_thresholds |>
  slice(101:200) |>
  write_csv("../../data/for hand checking/checked for false positives/non thresholds ian.csv")

```