---
title: "An excess of Cronbach's α values at rule-of-thumb cut-offs"
subtitle: "Precision of Cronbach's alpha = .70 across sample size and number of items"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

# TODO

- NA

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

# Dependencies

```{r}

library(cocron)
library(dplyr)
library(tidyr)
library(janitor)
library(knitr)
library(kableExtra)

# disable scientific notation
options(scipen=999)

```

# Distribution of number of items per scale in the psychology literature

Using APA PsycTests database.

```{r}

items <- c(3, 5, 10, 15, 20, 25, 50, 100)
cumulative_percent <- c(5.8, 14.8, 34.7, 50.1, 63.5, 73.1, 92.5, 98.0) # taken from psyctests_number_of_scale_items.Rmd

tab <- data.frame(items = items,
                  cumulative_percent)

tab |>
  kable(caption = "k items per scale & the cumulative % of all measures in APA PsycTests with up to k items") |>
  kable_classic(full_width = FALSE) 

```

# Standard Error of Cronbach's α = .70

```{r}

n <- c(50, 100, 250, 500, 1000, 2000, 5000)

dat <- NULL

for(i in n){
  for(j in items){
    CIs <- cronbach.alpha.CI(alpha = .70, n = i, items = j)
    res <- tibble(n = i, items = j, CI_lower = CIs[1], CI_upper = CIs[2])
    dat <- bind_rows(dat, res)
  }
}

dat_reshaped <- dat |>
  mutate(se = (CI_upper - CI_lower)/(1.96*2),
         se = janitor::round_half_up(se, 3)) |>
  select(n, items, se) |>
  pivot_wider(names_from = items, 
              values_from = se)

dat_reshaped |>
  kable(caption = "Standard Error of Cronbach's α = .70") |>
  kable_classic(full_width = FALSE) |>
  add_header_above(c(" " = 1, "k items" = ncol(dat_reshaped)-1))

```

```{r}

dat_reshaped2 <- dat |>
  mutate(se = (CI_upper - CI_lower)/(1.96*2),
         se = janitor::round_half_up(se, 3)) |>
  select(n, items, se) |>
  pivot_wider(names_from = n, 
              values_from = se)

dat_reshaped2 |>
  rename(`k items` = items) |>
  kable(caption = "Standard Error of Cronbach's α = .70") |>
  kable_classic(full_width = FALSE) |>
  add_header_above(c(" " = 1, "n participants" = ncol(dat_reshaped2)-1))

```

# Minimum sample size required to detect differences between Cronbach's α .69 vs .70

N found manually via experimentation

```{r}

n <- 14300

cocron.two.coefficients(alpha = c(.69, .70), 
                        n = c(n, n))

```

n in each sample = `r n`

# Session info

```{r}

sessionInfo()

```
