---
title: "Alpha curve"
subtitle: "Analyses"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

# Dependencies

```{r}

library(tidyverse)
library(broom)            
library(betareg)          
library(extraDistr) 
library(patchwork)

```

# Get data

```{r}

data_processed <- read_csv("../../data/processed/data_processed.csv")

data_processed_trimmed <- data_processed |>
  drop_na() 

```

# Descriptives

```{r}

n_doi <- data_processed |>
  distinct(doi) |>
  count(name = "n_doi") 

paste("n articles =", 
      n_doi)


n_exclusions <- data_processed |>
  filter(exclude_master == TRUE) |>
  count(name = "n_exclusions")

paste("n exclusions =", 
      n_exclusions)


n_estimates_after_exclusions <- data_processed_trimmed |>
  count(name = "n_estimates")

paste("n alpha estimates after exclusions =", 
      n_estimates_after_exclusions)


proportion_with_valid_alpha <- 
  janitor::round_half_up(pull(n_estimates_after_exclusions, n_estimates) / pull(n_doi, n_doi), 2)

paste("proportion of articles with 1+ alpha estimates after exclusions =",
      proportion_with_valid_alpha)

```

# Kernal smoothing

```{r fig.height=6, fig.width=6}

data_frequency_temp <- data_processed_trimmed %>% 
  mutate(alpha = janitor::round_half_up(alpha, 2),
         alpha = case_when(alpha == 0 ~ 0.01,
                           alpha == 1 ~ 0.99,
                           TRUE ~ alpha)) %>% 
  mutate(n_total = n()) %>% 
  group_by(alpha) %>% 
  summarise(freq = sum(!is.na(alpha))/first(n_total)) %>%
  mutate(alpha = as.character(alpha)) 

# all_alphas <- tibble(alpha = seq(0.01,0.99,0.01))
# 
# x <- anti_join(all_alphas, data_frequency, by = "alpha")
# 
# temp <- data_frequency %>% 
#   bind_rows(data_frequency, anti_join(all_alphas, data_frequency, by = "alpha")) %>%
#   arrange(alpha, desc(freq)) %>%
#   mutate(freq = ifelse(is.na(freq), 0, freq))

all_alphas <- tibble(alpha = as.character(seq(0.01,0.99,0.01)), freq = 0)

data_frequency <- data_frequency_temp %>% 
  bind_rows(all_alphas %>% anti_join(data_frequency_temp, by = "alpha")) %>% 
  arrange(alpha, desc(freq)) %>% 
  distinct(alpha, .keep_all = TRUE)
  
# ggplot(data_frequency, aes(alpha, freq)) + 
#   geom_col()

temp <- density(data_processed_trimmed$alpha, 
                n = length(seq(0.01, 0.99, 0.01)), 
                from = 0.01, 
                to = 0.99)

data_frequency$density <- temp$y

# data_frequency$fitted <- 
#   extraDistr::dprop(x = data_frequency$alpha, 
#                     size = exp(beta_phi_intercept), 
#                     mean = plogis(beta_mu_intercept))
# data_frequency$fitted <- dbeta(x = data_frequency$alpha, shape2 =  (beta_phi_intercept), 
# shape1 = (beta_mu_intercept))

# ggplot(data_frequency, aes(alpha, 100*freq)) + 
#  geom_step(aes(y = density)) + 
#  geom_col()

data_frequency <- data_frequency %>% 
  mutate(residual = freq*100 - density,
         alpha = as.numeric(alpha))

# ggplot(data_frequency, aes(alpha)) + 
#   geom_col(aes(y = freq*100)) +
#   geom_line(aes(y = fitted))

diff <- data_frequency %>% 
  mutate(frequency = 100*freq,
         frequencyworesidual = if_else(residual > 0, frequency - residual, frequency),
         pos_resid = residual > 0,
         residual = if_else(residual > 0, residual, -1 * residual)) %>% 
  dplyr::select(alpha, 
                #fitted, 
                density, 
                pos_resid, 
                frequencyworesidual, 
                residual) %>% 
  pivot_longer(c(frequencyworesidual, residual))


color_1 <- scales::viridis_pal()(11)[3]
color_2 <- scales::viridis_pal()(11)[7]

p1 <- 
  diff %>%  
  mutate(name = factor(case_when(
    name == "frequencyworesidual" ~ "3", 
    pos_resid ~ "2",
    TRUE ~ "1"))
  ) %>% 
  ggplot(., aes(alpha)) + 
  geom_vline(xintercept = c(0.7, 0.8, 0.9), linetype = "dotted") +
  geom_col(aes(y = value, fill = name), position = "stack") +
  geom_step(aes(y = density), direction = "mid") +
  #geom_step(aes(y = fitted)) +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = 0.1),
                     labels = seq(from = 0, to = 1, by = 0.1),
                     minor_breaks = NULL) +
  scale_fill_manual(values = c("3" = "lightgray", "2" = color_2, "1" = color_1), guide = "none") +
  #scale_fill_viridis_d(begin = .3, end = .7) +
  theme_bw() +
  labs(x = expression("Cronbach's" ~ alpha),
       y = "Kernal density")

p2 <- 
  ggplot(data_frequency, aes(alpha, residual, fill = residual > 0)) + 
  geom_vline(xintercept = c(0.7, 0.8, 0.9), linetype = "dotted") +
  geom_col() +
  #scale_fill_manual(values = c("3" = "gray", "2" = color_2, "1" = color_1), guide = "none") +
  scale_fill_viridis_d(begin = .3, end = .7) +
  scale_y_continuous(breaks = seq(from = -0.3, to = 0.3, by = 0.1),
                     labels = seq(from = -0.3, to = 0.3, by = 0.1),
                     minor_breaks = NULL) +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = 0.1),
                     labels = seq(from = 0, to = 1, by = 0.1),
                     minor_breaks = NULL) +
  theme_bw() +
  labs(x = expression("Cronbach's" ~ alpha),
       y = "Residual") +
  theme(legend.position = "none")

p1 + p2 + plot_layout(nrow = 2)

```

- geom_step(aes(y = density) or geom_step(aes(y = fitted) ? are both plots using same residuals?

# Beta regression

```{r}

# sultion from https://www.andrewheiss.com/blog/2021/11/08/beta-regression-guide/#interpreting-coefficients
      
model_beta <- data_processed_trimmed |>
  mutate(alpha = janitor::round_half_up(alpha, 2),
         alpha = case_when(alpha == 0 ~ 0.01,
                           alpha == 1 ~ 0.99,
                           TRUE ~ alpha)) |>
  betareg(alpha ~ 1 | 1, data = _, 
          link = "logit")

beta_mu_intercept <- model_beta %>% 
  tidy() %>% 
  filter(component == "mean", term == "(Intercept)") %>% 
  pull(estimate)

# # average alpha according to model
# plogis(beta_mu_intercept)
# ## [1] 0.8174543

beta_phi_intercept <- model_beta %>% 
  tidy() %>% 
  filter(component == "precision", term == "(Intercept)") %>% 
  pull(estimate)

# plot histogram and beta regression fit
ggplot(data = tibble(alpha = 0:1), aes(x = alpha)) + 
  geom_histogram(data = data_processed_trimmed,
                 aes(y = ..density..), 
                 binwidth = 0.01, 
                 fill = "#21908CFF") +
  stat_function(fun = extraDistr::dprop, size = 1,
                args = list(size = exp(beta_phi_intercept), 
                            mean = plogis(beta_mu_intercept))) +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = 0.1),
                     labels = seq(from = 0, to = 1, by = 0.1),
                     minor_breaks = NULL) +
  theme_bw() +
  labs(x = expression("Cronbach's" ~ alpha),
       y = "Density")

```

## Plot alpha curve & residuals

```{r}

data_frequency <- data_processed_trimmed %>% 
  mutate(alpha = janitor::round_half_up(alpha, 2),
         alpha = case_when(alpha == 0 ~ 0.01,
                           alpha == 1 ~ 0.99,
                           TRUE ~ alpha)) %>% 
  mutate(n_total = n()) %>% 
  group_by(alpha) %>% 
  summarise(freq = n()/first(n_total)) %>%
  mutate(fitted = extraDistr::dprop(x = alpha, 
                                    size = exp(beta_phi_intercept), 
                                    mean = plogis(beta_mu_intercept)),
         residual = freq*100 - fitted)

# ggplot(data_frequency, aes(alpha)) + 
#   geom_col(aes(y = freq*100)) +
#   geom_line(aes(y = fitted))

data_diff <- data_frequency %>% 
  mutate(frequency = 100*freq,
         frequencyworesidual = if_else(residual > 0, frequency - residual, frequency),
         pos_resid = residual > 0,
         residual = if_else(residual > 0, residual, -1 * residual)) %>% 
  dplyr::select(alpha,fitted, pos_resid, frequencyworesidual, residual) %>% 
  pivot_longer(c(-alpha, -fitted, -pos_resid))

data_diff %>%  
  mutate(name = factor(case_when(
    name == "frequencyworesidual" ~ "3", 
    pos_resid ~ "2",
    TRUE ~ "1"
  ))) %>% 
  ggplot(., aes(alpha)) + 
  geom_vline(xintercept = c(0.7, 0.8, 0.9), linetype = "dotted") +
  geom_col(aes(y = value, fill = name), position = "stack") +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = 0.1),
                     labels = seq(from = 0, to = 1, by = 0.1),
                     minor_breaks = NULL) +
  scale_fill_manual(values = c("3" = "lightgray", "2" = "#a46657", "1" = "#697d4f"), guide = "none") +
  geom_step(aes(y = fitted)) +
  theme_bw() +
  labs(x = expression("Cronbach's" ~ alpha),
       y = "Kernal density")

ggplot(data_frequency, aes(alpha, residual, fill = residual > 0)) + 
  geom_vline(xintercept = c(0.7, 0.8, 0.9), linetype = "dotted") +
  geom_col() +
  scale_x_continuous(breaks = seq(from = 0, to = 1, by = 0.1),
                     labels = seq(from = 0, to = 1, by = 0.1),
                     minor_breaks = NULL) +
  scale_fill_viridis_d(begin = .3, end = .7) +
  theme_bw() +
  labs(x = expression("Cronbach's" ~ alpha),
       y = "Residual")

```

# Stacked alphas 

## Plot

```{r}

data_processed_recentered <- 
  data_processed_trimmed |>
  mutate(tranch = case_when(              alpha <= .65 ~ "0.00 < alpha <= 0.65",
                            .65 < alpha & alpha <= .75 ~ "0.65 < alpha <= 0.75",
                            .75 < alpha & alpha <= .85 ~ "0.75 < alpha <= 0.85",
                            .85 < alpha & alpha <= .95 ~ "0.85 < alpha <= 0.95",
                            .95 < alpha                ~ "0.95 < alpha <= 1.00")) |>
  mutate(alpha_centered = case_when(tranch == "0.65 < alpha <= 0.75" ~ alpha - .7,
                                    tranch == "0.75 < alpha <= 0.85" ~ alpha - .8,
                                    tranch == "0.85 < alpha <= 0.95" ~ alpha - .9,
                                    TRUE ~ NA_real_))

data_processed_recentered |>
  filter(alpha_centered > -0.045) |>
  ggplot(aes(x = alpha_centered, fill = fct_rev(tranch))) +
  geom_vline(xintercept = 0, linetype = "dotted") +
  geom_histogram(position = "stack", binwidth = 0.01) +
  scale_x_continuous(breaks = seq(from = -0.05, to = 0.06, by = 0.01),
                     labels = seq(from = -0.05, to = 0.06, by = 0.01)) +
  coord_cartesian(xlim = c(-0.045, 0.055)) +
  labs(fill = "Tranch") +
  scale_fill_viridis_d(begin = 0.3, 
                       end = 0.7,
                       option = "magma",
                       labels = c(expression("0.85 <" ~ alpha ~ "<= 0.95"),
                                  expression("0.75 <" ~ alpha ~ "<= 0.85"),
                                  expression("0.65 <" ~ alpha ~ "<= 0.75"))) +
  theme_bw() +
  labs(x = expression("Cronbach's" ~ alpha ~ "(centered within each tranch)"),
       y = "Count")

```

# Session info

```{r}

sessionInfo()

```
