---
title: "Proporition of articles in journals/fields reporting one or more alpha estimates"
subtitle: "Analyses of Psychology/APA dataset"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

# TODO

- NA

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, 
                      warning = FALSE)

```

# Dependencies

```{r}

library(tidyverse)
library(knitr)
library(kableExtra)
library(janitor)

```

# Data

```{r}

data_fulltexts <- read_rds("../../data/raw/psychology/data_fulltexts.rds")

```

# DOIs with alphas

```{r}

data_dois_with_alpha <- 
  read_csv("../../data/processed/psychology/data_processed_psychology.csv") |>
  filter(!is.na(alpha) & exclude_master == FALSE) |>
  distinct(doi) |>
  mutate(alpha = TRUE)

data_fulltexts <- 
  read_rds("../../data/raw/psychology/data_fulltexts.rds") 

data_dois_without_alpha <- data_fulltexts |>
  select(doi)

data_alphas <- 
  full_join(data_dois_with_alpha, data_dois_without_alpha, by = "doi") |>
  mutate(alpha = ifelse(is.na(alpha), FALSE, alpha)) |>
  # drop missing dois
  filter(str_starts(doi, "nodoi", negate = TRUE))

#write_csv(data_dois, "../../data/processed/psychology/data_processed_dois.csv")

```

# DOIs with journals

```{r}

data_journals_and_fields <- read_rds("../../data/processed/psychology/data_journals_and_fields.rds")

```

# Compare

## Journals

```{r}

data_journals_alphas_fields |>
  mutate(journal = !is.na(journal),
         alpha = !is.na(alpha)) |>
  count(journal, alpha)

summary_journals <- data_journals_alphas_fields |>
  count(journal, alpha) |>
  group_by(journal) |>
  summarize(n_articles = sum(n),
            percent_with_alpha = janitor::round_half_up(n[alpha==TRUE]/sum(n)*100, 1), 
            .groups = "drop") |>
  arrange(desc(percent_with_alpha))

summary_journals |>
  kable() |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

## Fields

```{r}

data_journals_alphas_fields |>
  mutate(journal = !is.na(journal),
         alpha = !is.na(alpha)) |>
  count(journal, alpha)

summary_fields <- data_journals_alphas_fields |>
  count(field, alpha) |>
  group_by(field) |>
  summarize(n_articles = sum(n),
            percent_reporting_cronbachs_alpha = janitor::round_half_up(n[alpha==TRUE]/sum(n)*100, 1), 
            .groups = "drop") |>
  arrange(desc(percent_reporting_cronbachs_alpha))

summary_fields |>
  kable() |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

summary_fields |>
  filter(field %in% c("clincial", "personality/social", "cognitive", "developmental", "educational", "applied", "cognitive/experimental", "health")) |>
  rename(journal_category = field) |>
  kable() |>
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)

```

# Session info

```{r}

sessionInfo()

```
